/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteRouteImport } from './routes/create/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulateSlugRouteImport } from './routes/simulate/$slug'

const CreateRouteRoute = CreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateSlugRoute = SimulateSlugRouteImport.update({
  id: '/simulate/$slug',
  path: '/simulate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteRoute
  '/simulate/$slug': typeof SimulateSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteRoute
  '/simulate/$slug': typeof SimulateSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteRoute
  '/simulate/$slug': typeof SimulateSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/simulate/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/simulate/$slug'
  id: '__root__' | '/' | '/create' | '/simulate/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRouteRoute: typeof CreateRouteRoute
  SimulateSlugRoute: typeof SimulateSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate/$slug': {
      id: '/simulate/$slug'
      path: '/simulate/$slug'
      fullPath: '/simulate/$slug'
      preLoaderRoute: typeof SimulateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRouteRoute: CreateRouteRoute,
  SimulateSlugRoute: SimulateSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
